# Generated by Django 4.2.1 on 2023-05-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('idTrabajo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreTrabajo', models.CharField(max_length=80)),
                ('mecanico', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webSBLS.categoria')),
            ],
        ),
    ]
