# Generated by Django 4.2.1 on 2023-05-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSBLS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos'),
        ),
    ]
