# Generated by Django 4.2.1 on 2023-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSBLS', '0002_trabajo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='foto',
            field=models.ImageField(default='fotos/auto_default.jpg', null=True, upload_to='fotos'),
        ),
    ]
