# Generated by Django 4.1.5 on 2023-05-23 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSBLS', '0005_trabajo_anno_trabajo_marca_trabajo_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='anno',
            new_name='annov',
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='marca',
            new_name='marcav',
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='modelo',
            new_name='modelov',
        ),
    ]
