# Generated by Django 4.2.1 on 2023-05-26 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webSBLS', '0006_rename_anno_trabajo_annov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='idTrabajo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Galeriaimg',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='galeria')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webSBLS.trabajo')),
            ],
        ),
    ]
