# Generated by Django 4.2.3 on 2023-07-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSBLS', '0008_trabajo_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='precio',
            new_name='preciv',
        ),
    ]
