# Generated by Django 4.2.3 on 2023-07-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSBLS', '0009_rename_precio_trabajo_preciv'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=100)),
                ('correop', models.CharField(max_length=100)),
                ('mensajep', models.TextField(null=True)),
            ],
        ),
    ]
