# Generated by Django 4.2.3 on 2023-07-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSBLS', '0010_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contacto',
        ),
    ]
