# Generated by Django 5.0.4 on 2024-06-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webSBLS', '0013_rename_mecanico_trabajo_usuarioreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(upload_to='categoria_fotos/'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
